/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuloAdministrador;
import clases.MetPreguntas; 
import clases.Pregunta; 
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Preguntas extends javax.swing.JInternalFrame {

    DefaultTableModel tabla = new DefaultTableModel();
    Pregunta pregunta = new Pregunta();
    MetPreguntas mpregunta = new MetPreguntas();
    public Preguntas() {
        initComponents();
        ListarPreguntas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPregunta = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setText("PANTALLA DE PREGUNTAS");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel7.setText("Pregunta");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel8.setText("Descripcion");

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/diskette_save_saveas_1514.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1497619949-jd13_85182.png"))); // NOI18N
        btnActualizar.setText("Acualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/emblemunreadable_93487.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/emblemunreadable_93487.png"))); // NOI18N
        btnActivar.setText("Activar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        txtID.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel5.setText("Codigo");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Pregunta", "Descripcion", "Estado"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        txtPregunta.setColumns(20);
        txtPregunta.setRows(5);
        jScrollPane2.setViewportView(txtPregunta);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActivar)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void ListarPreguntas(){
     List<Pregunta> Listarpregunta = mpregunta.ListarPreguntas();
        tabla = (DefaultTableModel) Tabla.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < Listarpregunta.size(); i++) {
            ob[0] = Listarpregunta.get(i).getCodigo();
            ob[1] = Listarpregunta.get(i).getPregunta();
            ob[2] = Listarpregunta.get(i).getDescripcion();
            ob[3] = Listarpregunta.get(i).getEstado(); 
            tabla.addRow(ob);
        }
        Tabla.setModel(tabla);
    }
    
    public void Habilitar(){
       txtPregunta.setEnabled(true);
       txtDescripcion.setEnabled(true);
       //txtDireccion.setEnabled(true);
    }
    
    public void Deshabilitar(){
       txtPregunta.setEnabled(false);
       txtDescripcion.setEnabled(false);
       //txtDireccion.setEnabled(false);
    }
    
    public void LimpiarCampos(){
        txtID.setText("");
        txtPregunta.setText("");
        txtDescripcion.setText("");
        //txtDireccion.setText("");
    }
    
     public void LimpiarTabla()
     {
        for (int i = 0; i < tabla.getRowCount(); i++) {
           tabla.removeRow(i);
           i=i-1;
        }
     }
     
     public static boolean isBlank(String str)
    {
        return str.trim().isEmpty();
    }
     
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        Habilitar();
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String Usuario = txtPregunta.getText();
        String Contrasena = txtDescripcion.getText();

        if(isBlank(Usuario) || isBlank(Contrasena) ){
            JOptionPane.showMessageDialog(null,"Los campos estan vacios");
            Deshabilitar();
        }else{
            pregunta.setPregunta(Usuario);
            pregunta.setDescripcion(Contrasena);
            pregunta.setEstado("activo"); 
            mpregunta.RegistrarPreguntas(pregunta);
            JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
            LimpiarTabla();
            LimpiarCampos();
            Deshabilitar();
            btnActualizar.setEnabled(true);
            btnEliminar.setEnabled(true);
            ListarPreguntas();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked

    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String codigo = txtID.getText();
        String Usuario = txtPregunta.getText();
        String Contrasena = txtDescripcion.getText();
        //String telefono = txtTelefono.getText();

        if(isBlank(codigo)){
            JOptionPane.showMessageDialog(null, "Seleccione la fila para actualizar");
        }else{
            if(isBlank(Usuario) || isBlank(Contrasena) ){

            }else{
                pregunta.setPregunta(Usuario);
                pregunta.setDescripcion(Contrasena);
                //pregunta.setDireccion_proveedor(direccion);
                pregunta.setCodigo(Integer.parseInt(codigo));
                mpregunta.ModificarPreguntas(pregunta);

                LimpiarTabla();
                ListarPreguntas();
                LimpiarCampos();
                JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
                Deshabilitar();
                btnGuardar.setEnabled(true);
                btnNuevo.setEnabled(true);
                btnActualizar.setEnabled(true);
                btnEliminar.setEnabled(true);

            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigo = txtID.getText();

        if(isBlank(codigo)){
            JOptionPane.showMessageDialog(null, "Seleccione la fila a eliminar");
        }else{
            int confirmacion = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar");
            if(confirmacion == 0){
                int id = Integer.parseInt(txtID.getText());
                mpregunta.EliminarPreguntas(id);
                LimpiarTabla();
                LimpiarCampos();
                ListarPreguntas();
                Deshabilitar();
                btnGuardar.setEnabled(true);
                btnNuevo.setEnabled(true);
                btnActualizar.setEnabled(true);
                btnEliminar.setEnabled(true);

            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        // TODO add your handling code here:
        String codigo = txtID.getText();

        if(isBlank(codigo)){
            JOptionPane.showMessageDialog(null, "Seleccione la fila a activar");
        }else{
            int confirmacion = JOptionPane.showConfirmDialog(null, "Esta seguro de activar");
            if(confirmacion == 0){
                int id = Integer.parseInt(txtID.getText());
                mpregunta.ActivarPreguntas(id);
                LimpiarTabla();
                LimpiarCampos();
                ListarPreguntas();
                Deshabilitar();
                btnGuardar.setEnabled(true);
                btnNuevo.setEnabled(true);
                btnActualizar.setEnabled(true);
                btnActivar.setEnabled(true);

            }
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        Habilitar();
        int fila = Tabla.rowAtPoint(evt.getPoint());

        txtID.setText(Tabla.getValueAt(fila, 0).toString());
        txtPregunta.setText(Tabla.getValueAt(fila, 1).toString());
        txtDescripcion.setText(Tabla.getValueAt(fila, 2).toString());
        //txtTelefono.setText(Tabla.getValueAt(fila, 2).toString());
        //txtDireccion.setText(Tabla.getValueAt(fila, 3).toString());
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_TablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextArea txtPregunta;
    // End of variables declaration//GEN-END:variables
}
